plugins {
    id "com.android.application"
}

android {
    namespace "com.presenca911.sensor"
    compileSdk 35

    defaultConfig {
        applicationId "com.presenca911.sensor"
        minSdk 26
        targetSdk 35
        versionCode 2
        versionName "2.0.0"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile("proguard-android-optimize.txt"), "proguard-rules.pro"
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation "com.google.mlkit:text-recognition:16.0.1"
}
